export const UPDATE_SIDEBAR_STATE = 'UPDATE_SIDEBAR_STATE'
export const CLOSE_SIDEBAR = 'CLOSE_SIDEBAR'
export const OPEN_SIDEBAR = 'OPEN_SIDEBAR'

export const UPDATE_CURRENT_SECTION = 'UPDATE_CURRENT_SECTION'